/** Every server path in one place. ok */
export const ENDPOINTS = {
  products: '/products',
  product: (slug) => `/products/${slug}`,
  reviews: (slug) => `/products/${slug}/reviews`,
  departments: '/departments',
  categories: '/categories',
  brands: '/brands',
  collections: '/collections',
  collection: (slug) => `/collections/${slug}`,
  search: '/search',
  cart: '/cart',
  coupon: (code) => `/cart/coupons/${code}`,
  wishlist: '/wishlist',
  orders: '/orders',
  order: (id) => `/orders/${id}`,
  orderTracking: (id) => `/orders/${id}/tracking`,
  addresses: '/account/addresses',
  address: (id) => `/account/addresses/${id}`,
  profile: '/account/profile',
  paymentMethods: '/account/payment-methods',
  paymentIntent: '/payments/intent',
  paymentVerify: '/payments/verify',
  newsletter: '/newsletter/subscribe',
  contact: '/contact',
  login: '/auth/login',
  register: '/auth/register',
  logout: '/auth/logout',
  me: '/auth/me',
  forgotPassword: '/auth/forgot-password',
  verifyOtp: '/auth/verify-otp',
  resetPassword: '/auth/reset-password',
  instagram: '/instagram/feed',
}
